var Generator = require('yeoman-generator');
var path = require('path');

module.exports = class extends Generator {
  constructor(args, opts) {
    super(args, opts);

    // name of the app based on the directory name generated by React Native
    this.name = process.cwd().split(path.sep).pop();

    this.argument('screen', { type: String, required: true });
  }

  writing() {
    var screen = this.options.screen;

    this.fs.copyTpl(
      this.templatePath('index.tsx'),
      this.destinationPath(`App/Screens/${screen}.tsx`),
      {
        screen: screen,
        name: this.name,
        type: this.type,
      }
    );
  }

  end() {
    var screen = this.options.screen;

    this.log('Please make sure to add this to your screens export.');
    this.log('App/Screens/index.ts');
    this.log(`
      import ${screen} from "${this.name}/App/Screens/${screen}";

      export default {
        // ...other screens
        ${screen}: ${screen},
      };
    `);
  }
};
