var Generator = require('yeoman-generator');
var path = require('path');

module.exports = class extends Generator {
  constructor(args, opts) {
    super(args, opts);

    // name of the app based on the directory name generated by React Native
    this.name = process.cwd().split(path.sep).pop();

    this.argument('reducer', { type: String, required: true });
  }

  writing() {
    var reducer = this.options.reducer;
    var reducerConst = reducer.toUpperCase();
    var reducerSlug = reducer.toLowerCase();

    // create entry points for Android and iOS
    this.fs.copyTpl(
      this.templatePath('reducer.js'),
      this.destinationPath(`App/Reducers/${reducer}.js`),
      {
        name: this.name,
        reducer: reducer,
        reducerConst: reducerConst,
        reducerSlug: reducerSlug,
      }
    );

    this.fs.copyTpl(
      this.templatePath('actions.js'),
      this.destinationPath(`App/Actions/${reducer}.js`),
      {
        name: this.name,
        reducer: reducer,
        reducerConst: reducerConst,
        reducerSlug: reducerSlug,
      }
    );
  }

  end() {
    var reducer = this.options.reducer;
    var reducerConst = reducer.toUpperCase();
    var reducerSlug = reducer.toLowerCase();

    this.log('Please make sure to add this to your root reducer.');
    this.log('App/Reducers/index.js');
    this.log(`
      import ${reducer} from '${this.name}/App/Reducers/${reducer}';

      const reducers = combineReducers({
        // ...other reducers
        ${reducerSlug}: ${reducer},
      });
    `);
  }
};
